[project]
name = "apex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julien OPPLIGER", email = "account@oppliger.cc" }
]
requires-python = ">=3.13"
dependencies = [
    "common",
    "dnspython>=2.8.0",
]

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
common = { workspace = true }

[project.scripts]
apex = "apex.__main__:main"
