[project]
name = "common"
version = "0.0.1"
description = "Shared library for all graphrecon tools"
readme = "README.md"
authors = [
    { name = "Julien OPPLIGER", email = "account@oppliger.cc" }
]
requires-python = ">=3.13"
dependencies = [
    "dnspython>=2.8.0",
    "open-asset-store>=0.0.2",
    "termcolor>=3.3.0",
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
